-- ====================================================================
-- HackQubit 2.0 - Problem 18: Synthetic Student Seed Data
-- 60 diverse records across engineering departments, CGPAs, and skills
-- ====================================================================

INSERT INTO students (student_id, name, department, year, cgpa, email, skills, placement_status) VALUES
('STU001', 'Aarav Sharma', 'Computer Science', 4, 9.42, 'aarav.sharma@campus.edu', 'Python, PyTorch, AI, PostgreSQL, Docker', 'Placed'),
('STU002', 'Aditi Verma', 'Computer Science', 4, 8.85, 'aditi.verma@campus.edu', 'Java, Spring Boot, Microservices, Kubernetes', 'Placed'),
('STU003', 'Rohan Kulkarni', 'Artificial Intelligence & Data Science', 3, 9.15, 'rohan.kulkarni@campus.edu', 'Python, Machine Learning, Deep Learning, TensorFlow, NLP', 'Eligible'),
('STU004', 'Pooja Iyer', 'Information Technology', 4, 7.80, 'pooja.iyer@campus.edu', 'JavaScript, React, Node.js, MongoDB', 'Eligible'),
('STU005', 'Vikram Patel', 'Computer Science', 3, 8.60, 'vikram.patel@campus.edu', 'Go, Distributed Systems, Redis, Docker', 'Eligible'),
('STU006', 'Sneha Nair', 'Information Technology', 4, 8.35, 'sneha.nair@campus.edu', 'Angular, Python, AI, Django, AWS', 'Placed'),
('STU007', 'Karthik Raja', 'Electronics & Communication', 4, 7.90, 'karthik.raja@campus.edu', 'Embedded C, IoT, Python, Raspberry Pi', 'Eligible'),
('STU008', 'Meera Rao', 'Computer Science', 4, 9.78, 'meera.rao@campus.edu', 'Machine Learning, AI, Rust, C++, LLMs', 'Placed'),
('STU009', 'Arjun Das', 'Artificial Intelligence & Data Science', 3, 8.92, 'arjun.das@campus.edu', 'Computer Vision, OpenCV, PyTorch, AI', 'Eligible'),
('STU010', 'Ananya Gupta', 'Computer Science', 4, 9.20, 'ananya.gupta@campus.edu', 'Python, FastAPI, AWS, CI/CD, Docker', 'Placed'),
('STU011', 'Devansh Singhal', 'Mechanical Engineering', 4, 6.85, 'devansh.singhal@campus.edu', 'SolidWorks, AutoCAD, ANSYS, MATLAB', 'Eligible'),
('STU012', 'Rhea Chakraborty', 'Computer Science', 3, 8.40, 'rhea.c@campus.edu', 'TypeScript, Next.js, GraphQL, PostgreSQL', 'Eligible'),
('STU013', 'Siddharth Joshi', 'Artificial Intelligence & Data Science', 4, 9.55, 'siddharth.joshi@campus.edu', 'Natural Language Processing, AI, Transformers, Python, RAG', 'Placed'),
('STU014', 'Tanvi Mehta', 'Information Technology', 3, 7.45, 'tanvi.mehta@campus.edu', 'HTML, CSS, JavaScript, UI/UX, Figma', 'Eligible'),
('STU015', 'Nikhil Reddy', 'Electronics & Communication', 4, 8.10, 'nikhil.reddy@campus.edu', 'VLSI, Verilog, C++, MATLAB', 'Placed'),
('STU016', 'Ishita Bansal', 'Computer Science', 4, 8.75, 'ishita.bansal@campus.edu', 'Python, Django, React, AI, Machine Learning', 'Placed'),
('STU017', 'Gaurav Sen', 'Computer Science', 3, 9.05, 'gaurav.sen@campus.edu', 'System Design, C++, Redis, Apache Kafka', 'Eligible'),
('STU018', 'Priyanka Menon', 'Information Technology', 4, 8.25, 'priyanka.menon@campus.edu', 'Cloud Computing, AWS, Terraform, Docker, Python', 'Placed'),
('STU019', 'Harsh Vardhan', 'Civil Engineering', 4, 6.70, 'harsh.vardhan@campus.edu', 'AutoCAD, Revit, Structural Analysis, Project Management', 'Not Eligible'),
('STU020', 'Kavya S', 'Artificial Intelligence & Data Science', 4, 9.30, 'kavya.s@campus.edu', 'Data Science, Pandas, Scikit-learn, AI, PowerBI', 'Placed'),
('STU021', 'Manish Tiwari', 'Mechanical Engineering', 3, 7.15, 'manish.tiwari@campus.edu', 'CAD/CAM, Python, Robotics, ROS', 'Eligible'),
('STU022', 'Divya Suresh', 'Computer Science', 4, 8.95, 'divya.suresh@campus.edu', 'Cybersecurity, Ethical Hacking, Network Security, Python', 'Placed'),
('STU023', 'Abhinav Saxena', 'Information Technology', 3, 8.15, 'abhinav.saxena@campus.edu', 'Full Stack Development, MERN, Docker', 'Eligible'),
('STU024', 'Neha Deshmukh', 'Electronics & Communication', 4, 8.50, 'neha.deshmukh@campus.edu', 'Digital Signal Processing, Python, Embedded Systems', 'Placed'),
('STU025', 'Varun Kapoor', 'Computer Science', 3, 7.60, 'varun.kapoor@campus.edu', 'Java, Android, Kotlin, SQLite', 'Eligible'),
('STU026', 'Shruti Saxena', 'Artificial Intelligence & Data Science', 3, 8.70, 'shruti.saxena@campus.edu', 'Reinforcement Learning, Python, PyTorch, AI', 'Eligible'),
('STU027', 'Rahul Ghosh', 'Civil Engineering', 4, 6.40, 'rahul.ghosh@campus.edu', 'Surveying, GIS, AutoCAD, Primavera', 'Not Eligible'),
('STU028', 'Deepak Chopra', 'Computer Science', 4, 9.60, 'deepak.chopra@campus.edu', 'Algorithms, C++, Competitive Programming, Graph Theory', 'Placed'),
('STU029', 'Ayesha Khan', 'Information Technology', 4, 8.65, 'ayesha.khan@campus.edu', 'DevOps, Jenkins, Kubernetes, Helm, Bash', 'Placed'),
('STU030', 'Kunal Shah', 'Mechanical Engineering', 4, 7.85, 'kunal.shah@campus.edu', 'Automotive Engineering, Thermodynamics, MATLAB, Python', 'Eligible'),
('STU031', 'Simran Kaur', 'Artificial Intelligence & Data Science', 4, 9.10, 'simran.kaur@campus.edu', 'Deep Learning, AI, Computer Vision, YOLO, Python', 'Placed'),
('STU032', 'Tarun Jain', 'Computer Science', 3, 8.20, 'tarun.jain@campus.edu', 'Node.js, Express, PostgreSQL, Microservices', 'Eligible'),
('STU033', 'Bhavna Pandey', 'Electronics & Communication', 3, 7.35, 'bhavna.pandey@campus.edu', 'Microcontrollers, Arduino, C, Python', 'Eligible'),
('STU034', 'Akash Nambiar', 'Computer Science', 4, 8.90, 'akash.nambiar@campus.edu', 'Solidity, Web3, Smart Contracts, Ethereum', 'Placed'),
('STU035', 'Pallavi Sen', 'Information Technology', 3, 8.55, 'pallavi.sen@campus.edu', 'Python, Data Analytics, Tableau, SQL', 'Eligible'),
('STU036', 'Yash Singhal', 'Computer Science', 4, 9.35, 'yash.singhal@campus.edu', 'Kubernetes, Cloud Native, Go, Docker, AI', 'Placed'),
('STU037', 'Sanjana Pillai', 'Artificial Intelligence & Data Science', 3, 8.80, 'sanjana.pillai@campus.edu', 'LLMs, Prompt Engineering, LangChain, Python, AI', 'Eligible'),
('STU038', 'Rajat Malhotra', 'Mechanical Engineering', 4, 6.95, 'rajat.malhotra@campus.edu', 'Manufacturing, Quality Control, Six Sigma, Lean', 'Not Eligible'),
('STU039', 'Swati Bhat', 'Computer Science', 4, 8.45, 'swati.bhat@campus.edu', 'React Native, Mobile App Development, Firebase', 'Placed'),
('STU040', 'Pranav Hegde', 'Information Technology', 4, 9.00, 'pranav.hegde@campus.edu', 'Backend Engineering, Java, Spring, Kafka, Redis', 'Placed'),
('STU041', 'Ankit Biswas', 'Electronics & Communication', 4, 7.75, 'ankit.biswas@campus.edu', 'Wireless Communications, 5G, MATLAB, Python', 'Eligible'),
('STU042', 'Radhika Soni', 'Computer Science', 3, 8.30, 'radhika.soni@campus.edu', 'Vue.js, TailwindCSS, REST APIs, Python', 'Eligible'),
('STU043', 'Omkar Jadhav', 'Artificial Intelligence & Data Science', 4, 9.25, 'omkar.jadhav@campus.edu', 'Big Data, PySpark, Hadoop, Databricks, AI', 'Placed'),
('STU044', 'Tanya Grover', 'Civil Engineering', 3, 7.20, 'tanya.grover@campus.edu', 'Environmental Engineering, GIS, Hydrology', 'Eligible'),
('STU045', 'Mohit Agrawal', 'Computer Science', 4, 8.70, 'mohit.agrawal@campus.edu', 'Site Reliability, Linux, Ansible, Prometheus, Grafana', 'Placed'),
('STU046', 'Geetika Anand', 'Information Technology', 3, 8.10, 'geetika.anand@campus.edu', 'Software Testing, Selenium, Cypress, QA Automation', 'Eligible'),
('STU047', 'Soham Dutta', 'Artificial Intelligence & Data Science', 4, 9.40, 'soham.dutta@campus.edu', 'Generative AI, Diffusion Models, PyTorch, AI, FastAPI', 'Placed'),
('STU048', 'Nandini Joshi', 'Computer Science', 3, 8.65, 'nandini.joshi@campus.edu', 'Full Stack, React, Node.js, PostgreSQL, Docker', 'Eligible'),
('STU049', 'Umesh Rao', 'Mechanical Engineering', 4, 7.50, 'umesh.rao@campus.edu', 'Mechatronics, Control Systems, Python, C++', 'Eligible'),
('STU050', 'Ritika Bhatt', 'Electronics & Communication', 4, 8.40, 'ritika.bhatt@campus.edu', 'FPGA Design, VHDL, Digital Electronics, C', 'Placed'),
('STU051', 'Vikas Goyal', 'Computer Science', 4, 7.95, 'vikas.goyal@campus.edu', 'Web Development, PHP, Laravel, MySQL', 'Eligible'),
('STU052', 'Shreya Mishra', 'Artificial Intelligence & Data Science', 3, 9.18, 'shreya.mishra@campus.edu', 'Data Engineering, dbt, Snowflake, Airflow, SQL', 'Eligible'),
('STU053', 'Alok Pandey', 'Civil Engineering', 4, 6.55, 'alok.pandey@campus.edu', 'Geotechnical Engineering, Soil Mechanics, AutoCAD', 'Not Eligible'),
('STU054', 'Jaya Varma', 'Information Technology', 4, 8.88, 'jaya.varma@campus.edu', 'Cloud Architecture, GCP, Terraform, Python, Kubernetes', 'Placed'),
('STU055', 'Madhav Namboodiri', 'Computer Science', 3, 8.72, 'madhav.n@campus.edu', 'Rust, WebAssembly, Systems Programming, C', 'Eligible'),
('STU056', 'Kritika Roy', 'Computer Science', 4, 9.50, 'kritika.roy@campus.edu', 'AI Research, Deep Learning, Graph Neural Networks, PyTorch', 'Placed'),
('STU057', 'Saurabh Jha', 'Electronics & Communication', 3, 7.65, 'saurabh.jha@campus.edu', 'Optical Communications, MATLAB, Python, Embedded C', 'Eligible'),
('STU058', 'Trisha Paul', 'Artificial Intelligence & Data Science', 4, 8.95, 'trisha.paul@campus.edu', 'Predictive Modeling, Time Series, Python, AI, XGBoost', 'Placed'),
('STU059', 'Chirag Sethi', 'Information Technology', 3, 8.05, 'chirag.sethi@campus.edu', 'Database Administration, PostgreSQL, Performance Tuning', 'Eligible'),
('STU060', 'Zoya Farooqui', 'Computer Science', 4, 9.65, 'zoya.f@campus.edu', 'Distributed Databases, Raft, Go, AI Infrastructure', 'Placed')
ON CONFLICT (student_id) DO NOTHING;

